# Generated by Django 4.1.3 on 2022-12-20 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0003_alter_cart_user_alter_comment_user_alter_sell_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sell',
            name='manga',
        ),
        migrations.RemoveField(
            model_name='sell',
            name='quantity',
        ),
        migrations.AddField(
            model_name='sell',
            name='status',
            field=models.IntegerField(default=0, verbose_name='Статус'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('manga', models.ForeignKey(db_column='manga', on_delete=django.db.models.deletion.DO_NOTHING, to='manga.manga', verbose_name='Манга')),
                ('sell', models.ForeignKey(db_column='sell', on_delete=django.db.models.deletion.DO_NOTHING, to='manga.sell', verbose_name='Продажа')),
            ],
        ),
    ]
