# Generated by Django 4.1.3 on 2022-12-26 10:14

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0004_remove_sell_manga_remove_sell_quantity_sell_status_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='date_modified',
        ),
        migrations.RemoveField(
            model_name='manga',
            name='date_modified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_modified',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='', max_length=20, verbose_name='Почта'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
