# Generated by Django 4.1.3 on 2022-12-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0005_alter_user_managers_remove_comment_date_modified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='sell',
            field=models.IntegerField(verbose_name='Номер заказа'),
        ),
    ]
