# Generated by Django 4.1.3 on 2022-12-26 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0006_alter_purchase_sell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='sell',
            field=models.ForeignKey(db_column='sell', on_delete=django.db.models.deletion.DO_NOTHING, to='manga.sell', verbose_name='Продажа'),
        ),
    ]
