# Generated by Django 4.1.2 on 2022-10-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0004_sell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='sell_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата продажи'),
        ),
    ]
