# Generated by Django 4.1.3 on 2022-11-29 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('manga', models.ForeignKey(db_column='manga', on_delete=django.db.models.deletion.DO_NOTHING, to='manga.manga', verbose_name='Манга')),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.DO_NOTHING, to='manga.user', verbose_name='Пользователь')),
            ],
        ),
    ]
