# Generated by Django 4.1.3 on 2022-12-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0002_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.IntegerField(verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.IntegerField(verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='sell',
            name='user',
            field=models.IntegerField(verbose_name='Пользователь'),
        ),
    ]
