# Generated by Django 4.1.2 on 2022-10-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(max_length=8000, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='images')),
            ],
            options={
                'verbose_name': 'Мангу',
                'verbose_name_plural': 'Манга',
                'db_table': 'mangas',
                'managed': False,
            },
        ),
    ]
