# Generated by Django 4.1.2 on 2022-10-25 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manga_lab', '0002_user_alter_manga_options_sell_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sell',
            name='manga',
        ),
        migrations.RemoveField(
            model_name='sell',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='manga',
            options={'managed': False, 'verbose_name': 'Мангу', 'verbose_name_plural': 'Манга'},
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Sell',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
